[package]
name = "zoku"
version = "0.1.3"
edition = "2024"
license = "MIT"
description = "Zoku is a minimalist terminal attach/detach tool"
homepage = "https://github.com/aiifabbf/zoku"
repository = "https://github.com/aiifabbf/zoku"
readme = "README.rst"
keywords = ["terminal-multiplexer"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
async-signal = "0.2.14"
nix = { version = "0.30.1", features = ["term", "process", "ioctl", "fs", "poll"] }
smol = "2.0.2"
